// Manually maintained champion role map.
// Keys are DDragon champion IDs. Values are arrays of role values: top, jg, mid, adc, sp.
// A champion can appear in multiple roles.

const championRoles = {
  // ── TOP ─────────────────────────────────────────────────────────────────────
  Aatrox: ["top"],
  Akali: ["top", "mid"],
  Akshan: ["top", "mid"],
  Camille: ["top"],
  Chogath: ["top"],
  Darius: ["top"],
  DrMundo: ["top"],
  Fiora: ["top"],
  Gangplank: ["top"],
  Garen: ["top"],
  Gnar: ["top"],
  Gragas: ["top", "jg"],
  Gwen: ["top"],
  Heimerdinger: ["top", "mid"],
  Illaoi: ["top"],
  Irelia: ["top", "mid"],
  Jax: ["top", "jg"],
  Jayce: ["top", "mid"],
  Kayle: ["top"],
  Kennen: ["top"],
  KSante: ["top"],
  Malphite: ["top"],
  Maokai: ["top", "sp"],
  Mordekaiser: ["top"],
  Nasus: ["top"],
  Nautilus: ["top", "sp"],
  Olaf: ["top", "jg"],
  Ornn: ["top"],
  Pantheon: ["top", "mid", "sp"],
  Poppy: ["top", "jg", "sp"],
  Quinn: ["top"],
  Renekton: ["top"],
  Rengar: ["top", "jg"],
  Riven: ["top"],
  Rumble: ["top"],
  Ryze: ["top", "mid"],
  Sett: ["top", "sp"],
  Shen: ["top", "sp"],
  Singed: ["top"],
  Sion: ["top"],
  TahmKench: ["top", "sp"],
  Teemo: ["top"],
  Trundle: ["top", "jg"],
  Tryndamere: ["top"],
  Udyr: ["top", "jg"],
  Urgot: ["top"],
  Vayne: ["top", "adc"],
  Vladimir: ["top", "mid"],
  Volibear: ["top", "jg"],
  Wukong: ["top", "jg"],
  Yasuo: ["top", "mid"],
  Yone: ["top", "mid"],
  Yorick: ["top"],

  // ── JUNGLE ──────────────────────────────────────────────────────────────────
  Amumu: ["jg", "sp"],
  Belveth: ["jg"],
  Briar: ["jg"],
  Diana: ["jg", "mid"],
  Ekko: ["jg", "mid"],
  Elise: ["jg"],
  Evelynn: ["jg"],
  FiddleSticks: ["jg", "sp"],
  Graves: ["jg"],
  Hecarim: ["jg"],
  Ivern: ["jg", "sp"],
  JarvanIV: ["jg"],
  Karthus: ["jg", "mid"],
  Kayn: ["jg"],
  Khazix: ["jg"],
  Kindred: ["jg"],
  LeeSin: ["jg"],
  Lillia: ["jg"],
  MasterYi: ["jg"],
  Nidalee: ["jg"],
  Nocturne: ["jg"],
  Nunu: ["jg"],
  Rammus: ["jg"],
  RekSai: ["jg"],
  Sejuani: ["jg"],
  Shaco: ["jg"],
  Shyvana: ["jg"],
  Skarner: ["jg"],
  Taliyah: ["jg", "mid"],
  Vi: ["jg"],
  Viego: ["jg"],
  Warwick: ["jg"],
  XinZhao: ["jg"],
  Zac: ["jg"],

  // ── MID ─────────────────────────────────────────────────────────────────────
  Ahri: ["mid"],
  Anivia: ["mid"],
  Annie: ["mid", "sp"],
  AurelionSol: ["mid"],
  Azir: ["mid"],
  Cassiopeia: ["mid"],
  Corki: ["mid"],
  Fizz: ["mid"],
  Galio: ["mid", "sp"],
  Kassadin: ["mid"],
  Katarina: ["mid"],
  LeBlanc: ["mid"],
  Lissandra: ["mid"],
  Lux: ["mid", "sp"],
  Malzahar: ["mid"],
  Naafiri: ["mid"],
  Neeko: ["mid", "sp"],
  Orianna: ["mid"],
  Qiyana: ["mid"],
  Seraphine: ["mid", "sp"],
  Swain: ["mid", "sp"],
  Sylas: ["mid"],
  Syndra: ["mid"],
  Talon: ["mid"],
  TwistedFate: ["mid"],
  Veigar: ["mid", "sp"],
  Velkoz: ["mid", "sp"],
  Vex: ["mid"],
  Viktor: ["mid"],
  Xerath: ["mid", "sp"],
  Zed: ["mid"],
  Ziggs: ["mid", "adc"],
  Zoe: ["mid"],
  Zyra: ["mid", "sp"],

  // ── ADC ─────────────────────────────────────────────────────────────────────
  Aphelios: ["adc"],
  Ashe: ["adc", "sp"],
  Caitlyn: ["adc"],
  Draven: ["adc"],
  Ezreal: ["adc"],
  Jinx: ["adc"],
  Kaisa: ["adc"],
  Kalista: ["adc"],
  KogMaw: ["adc"],
  Lucian: ["adc", "mid"],
  MissFortune: ["adc"],
  Nilah: ["adc"],
  Samira: ["adc"],
  Senna: ["adc", "sp"],
  Sivir: ["adc"],
  Smolder: ["adc"],
  Tristana: ["adc", "mid"],
  Twitch: ["adc", "jg"],
  Varus: ["adc", "mid"],
  Xayah: ["adc"],
  Zeri: ["adc"],

  // ── SUPPORT ─────────────────────────────────────────────────────────────────
  Alistar: ["sp"],
  Bard: ["sp"],
  Blitzcrank: ["sp"],
  Brand: ["sp", "mid"],
  Braum: ["sp"],
  Janna: ["sp"],
  Karma: ["sp", "mid"],
  Leona: ["sp"],
  Lulu: ["sp"],
  Milio: ["sp"],
  Morgana: ["sp", "mid"],
  Nami: ["sp"],
  Pyke: ["sp"],
  Rakan: ["sp"],
  Rell: ["sp"],
  Renata: ["sp"],
  Sona: ["sp"],
  Soraka: ["sp"],
  Thresh: ["sp"],
  Yuumi: ["sp"],
  Zilean: ["sp", "mid"],
};

export default championRoles;
